package mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    private String courseName;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    private Long universityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @return the value of PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @param courseName the value for PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }









    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public Long getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.COURSE.UNIVERSITY_ID
     *
     * @mbg.generated Mon May 02 20:43:56 EEST 2022
     */
    public void setUniversityId(Long universityId) {
        this.universityId = universityId;
    }
}