package mybatis.model;

public class University {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.CITY
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    private String city;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.NAME
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    private String name;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @return the value of PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @param id the value for PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.CITY
     *
     * @return the value of PUBLIC.UNIVERSITY.CITY
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.CITY
     *
     * @param city the value for PUBLIC.UNIVERSITY.CITY
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public void setCity(String city) {
        this.city = city;
    }





    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.NAME
     *
     * @return the value of PUBLIC.UNIVERSITY.NAME
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.NAME
     *
     * @param name the value for PUBLIC.UNIVERSITY.NAME
     *
     * @mbg.generated Mon May 30 20:43:56 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }




}